name: Run go tests
on:
  push:
  pull_request:

concurrency:
  group: golang-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.2
        uses: actions/setup-go@v1
        with:
          go-version: 1.2
        id: go
    
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Get dependencies
        run: go mod download
    
      - name: Run tests
        run: go test -p 1 -v -race ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}